name: 'Workflow: Maven Release: Prepare and Perform'
run-name: 'Workflow Run: Maven Release: Prepare and Perform'
on:
  workflow_dispatch:
    inputs:
      dryRun:
        default: true
        description: 'Dry run?'
        type: 'boolean'
      mvnDebug:
        default: false
        description: 'Debug?'
        type: 'boolean'
      pushToken:
        default: true
        description: 'Use PAT?'
        type: 'boolean'
jobs:
  job-mvn-release-prepare-perform:
    name: 'Job: Maven Release: Prepare and Perform'
    permissions:
      contents: 'write'
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'checkout'
        name: 'Step: Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: 'setup-java'
        name: 'Step: Set Up Java and Maven'
        uses: 'actions/setup-java@v3'
        with:
          cache: 'maven'
          distribution: 'temurin'
          gpg-passphrase: 'GPG_PASSPHRASE'
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          java-version: '11'
          mvn-toolchain-id: 'Temurin 11'
          mvn-toolchain-vendor: 'openjdk' # see ../../pom.xml
          server-id: 'sonatype-oss-repository-hosting' # see https://github.com/microbean/microbean-parent/blob/master/pom.xml#L38
          server-password: 'SONATYPE_OSSRH_PASSWORD'
          server-username: 'SONATYPE_OSSRH_USERNAME'
      - id: 'setup-gpg'
        name: 'Step: Set Up GPG'
        run: |
          echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf
      - id: 'setup-askpass'
        name: 'Step: Set Up GIT_ASKPASS'
        env:
          GIT_ASKPASS: '${{ runner.temp }}/.askpass'
        run: |
          install -m 700 /dev/null "${GIT_ASKPASS}" # atomically create empty file with appropriate permissions
          cat >> "${GIT_ASKPASS}" <<<'#!/bin/bash
          case "${1}" in
              Username*) exec echo x-access-token ;;
              Password*) exec echo "${PUSH_TOKEN}" ;;
          esac'
      - id: 'mvn-release-prepare-perform'
        name: 'Step: Maven Release: Prepare and Perform'
        env:
          DRY_RUN: '${{ inputs.dryRun }}'
          GIT_ASKPASS: '${{ runner.temp }}/.askpass'
          GIT_CURL_VERBOSE: 'true'
          GPG_PASSPHRASE: '${{ secrets.GPG_PASSPHRASE }}'
          MVN_DEBUG: ${{ inputs.mvnDebug && '-X' || '' }}
          PUSH_TOKEN : '${{ inputs.pushToken && secrets.PUSH_TOKEN || github.token }}' # critical; see ~/.askpass
          SCM_GIT_HTTPS_URL: 'scm:git:${{ github.server_url }}/${{ github.repository }}.git'
          SONATYPE_OSSRH_PASSWORD: '${{ secrets.SONATYPE_OSSRH_PASSWORD }}'
          SONATYPE_OSSRH_USERNAME: '${{ secrets.SONATYPE_OSSRH_USERNAME }}'
        run: |
          git config --global user.email 'ci@microbean.org'
          git config --global user.name 'microbean'
          mvn ${MVN_DEBUG} --batch-mode release:prepare release:perform -DdryRun="${DRY_RUN}" -Dscm.url="${SCM_GIT_HTTPS_URL}" -Darguments="-Dscmpublish.pubScmUrl=${SCM_GIT_HTTPS_URL}"
